### ISSUE TITLE
1.0.0-alpha1 fails build on docs.rs

### ISSUE THREAD

**Issue by kennylevinsen** [1wilkens/pam-sys#10]
Build log can be seen here: https://docs.rs/crate/pam-sys/1.0.0-alpha1/builds/198171

**Comment by 1wilkens** [comment]
Already reported in https://github.com/rust-lang/docs.rs/issues/479. I will try to prepare a PR soon!

**Comment by 1wilkens** [comment]
PR was accepted and docs are up @ https://docs.rs/pam-sys/1.0.0-alpha1/pam_sys/
