### ISSUE TITLE
Missing `pam_modutil_search_key`?

### ISSUE THREAD

**Issue by vlovich** [1wilkens/pam-sys#19]
Noticed this function but don't see the FFI binding in the docs.

**Comment by 1wilkens** [comment]
I guess you checked the 1.0.0-alpha4 version? I am not sure, why it is missing there. If I build the documentation locally, it is indeed found, but as pam differs wildly between platforms, I'd assume, that the build environment on `docs.rs` does not have it. Try building the docs locally and see if you have it on your system :)
